manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_espressif
          - littlefs
    - name: zlib
      url: https://github.com/HubertYGuan/zlib
      revision: zephyr
      path: modules/lib/zlib
    - name: pdfio
      url: https://github.com/HubertYGuan/pdfio
      revision: zephyr
      path: modules/lib/pdfio

  self:
    path: module-app
